name: MCP Security Lint
description: Run mcp-sec-lint, print console summary, and emit SARIF
inputs:
  path:
    description: Path to scan
    default: .
  fail-on:
    description: 'off | info | warning | error'
    default: error
  out:
    description: SARIF file output path
    default: mcp-sec.sarif
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    # Install the action's deps (in the action folder)
    - run: npm --prefix "${{ github.action_path }}" install --no-audit --no-fund
      shell: bash

    # 1) Generate SARIF (never fail this step)
    - name: MCP Lint (SARIF)
      run: node "${{ github.action_path }}/bin/mcp-sec-lint" --path "${{ inputs.path }}" --format sarif --out "${{ inputs.out }}" --fail-on off || true
      shell: bash

    # 2) Console run (controls pass/fail and shows messages in logs)
    - name: MCP Lint (console)
      run: node "${{ github.action_path }}/bin/mcp-sec-lint" --path "${{ inputs.path }}" --format console --fail-on "${{ inputs.fail-on }}"
      shell: bash
