name: MCP Security Checks
on:
  push:
  pull_request:
permissions:
  contents: read
  security-events: write   # needed to upload SARIF

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run MCP Security Lint
        uses: fonCki/mcp-sec-lint@v0.1.0
        with:
          path: .
          fail-on: warning   # job fails on warning or worse

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mcp-sec.sarif
